{
 "title": "# Items",
 "tags": [
  "factorio",
  "rate"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "TimeScale",
    "label": "TimeScale",
    "query": "Second : 1, Minute : 60, Hour : 3600"
   },
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values({__name__=~\"factorio_research_queue\"},force)"
    }
   },
   {
    "name": "helper_research_name",
    "label": "helper_research_name",
    "query": {
     "query": "query_result(factorio_research_queue{index=\"1\"})"
    }
   },
   {
    "name": "helper_research_level",
    "label": "helper_research_level",
    "query": {
     "query": "label_values(factorio_research_queue{index=\"1\",name=\"${helper_research_name}\"},level)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Science Rate / ${TimeScale}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Red",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"automation-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"automation-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Green",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"logistic-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"logistic-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Black",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"military-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"military-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Blue",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"chemical-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"chemical-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Purple",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"production-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"production-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Yellow",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"utility-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"utility-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "White",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"space-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"space-science-pack\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Research",
   "type": "stat",
   "description": "Progress of currently running research",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "factorio_research_queue{force=~\"${Force}\",index=\"1\",name=\"${helper_research_name}\",level=\"${helper_research_level}\"}",
     "legendFormat": "{{name}} {{level}}",
     "target": "randomWalk('myName')"
    }
   ]
  },
  { "title": "Circuit Rate / ${TimeScale}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Green",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"electronic-circuit\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"electronic-circuit\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Red",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"advanced-circuit\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"advanced-circuit\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Blue",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"processing-unit\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"processing-unit\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  { "title": "Material Rate / ${TimeScale}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Iron",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"iron-plate\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"iron-plate\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Copper",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"copper-plate\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"copper-plate\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Plastic",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"plastic-bar\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"plastic-bar\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Steel",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"steel-plate\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"steel-plate\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  { "title": "Component Rate / ${TimeScale}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Battery",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"battery\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"battery\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Flying Robot Frame",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"flying-robot-frame\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"flying-robot-frame\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Low Density Structure",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"low-density-structure\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"low-density-structure\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Rocket Control Unit",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"rocket-control-unit\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"rocket-control-unit\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Rocket Fuel",
   "type": "stat",
   "description": "Item production - consumption delta over ${TimeScale} seconds",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_item_production_output{name=\"rocket-fuel\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Consumption",
     "target": "randomWalk('myName')"
    },
    {
     "expr": "rate(factorio_item_production_input{name=\"rocket-fuel\"}[$__range]) * ${TimeScale}",
     "legendFormat": "Production",
     "target": "randomWalk('myName')"
    }
   ]
  }
 ]
}