{
 "title": "1.1 - Default: Electricity",
 "tags": [
  "factorio",
  "default"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values({__name__=~\"factorio_power_production_input|factorio_power_production_output\"},force)"
    }
   },
   {
    "name": "Network",
    "label": "Network",
    "query": {
     "query": "label_values({__name__=~\"factorio_power_production_input|factorio_power_production_output\"},network)"
    }
   },
   {
    "name": "Consumer",
    "label": "Consumer",
    "query": {
     "query": "label_values(factorio_power_production_input{force=~\"${Force}\",network=~\"^${Network}\"}, name)"
    }
   },
   {
    "name": "Producer",
    "label": "Producer",
    "query": {
     "query": "label_values(factorio_power_production_output{force=~\"${Force}\",network=~\"^${Network}\"},name)"
    }
   },
   {
    "name": "helper_top_consumer",
    "label": "helper_top_consumer",
    "query": {
     "query": "query_result(topk(6,sum by (name) (rate(factorio_power_production_input{force=~\"${Force}\",network=~\"^${Network}\",name=~\"^${Consumer}\"}[$__range]))))"
    }
   },
   {
    "name": "helper_top_producer",
    "label": "helper_top_producer",
    "query": {
     "query": "query_result(topk(6,sum by (name) (rate(factorio_power_production_output{force=~\"${Force}\",network=~\"^${Network}\",name=~\"^${Producer}\"}[$__range]))))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumption",
   "type": "timeseries",
   "description": "Electricity consumption",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(factorio_power_production_input{force=~\"${Force}\",name=~\"${Consumer}|${Producer}\",network=~\"${Network}\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Production",
   "type": "timeseries",
   "description": "Electricity production",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(factorio_power_production_output{force=~\"${Force}\",name=~\"${Consumer}|${Producer}\",network=~\"${Network}\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${helper_top_consumer}",
   "type": "stat",
   "description": "Overall consumed energy by ${helper_top_consumer}",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "repeat": "helper_top_consumer",
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (increase(factorio_power_production_input{force=~\"${Force}\",name=\"${helper_top_consumer}\",network=~\"${Network}\"}[$__range]))",
     "legendFormat": "${helper_top_consumer}"
    }
   ]
  },
  {
   "title": " Consumption",
   "type": "bargauge",
   "description": "Top energy consumer",
   "gridPos": { "h": 12, "w": 10, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,sum by (name) (rate(factorio_power_production_input{force=~\"${Force}\",name=~\"${Consumer}|${Producer}\",network=~\"${Network}\"}[$__range])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${helper_top_producer}",
   "type": "stat",
   "description": "Overall produced energy by ${helper_top_producer}",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 11 },
   "repeat": "helper_top_producer",
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (increase(factorio_power_production_output{force=~\"${Force}\",name=\"${helper_top_producer}\",network=~\"${Network}\"}[$__range]))",
     "legendFormat": "${helper_top_producer}"
    }
   ]
  },
  {
   "title": " Production",
   "type": "bargauge",
   "description": "Top energy producer",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,sum by (name) (rate(factorio_power_production_output{name=~\"${Consumer}|${Producer}\",network=~\"${Network}\"}[$__range])))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}