{
 "title": "1.3 - Default: Fluids",
 "tags": [
  "factorio",
  "default"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "TimeScale",
    "label": "TimeScale",
    "query": "Second : 1, Minute : 60, Hour : 3600"
   },
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values({__name__=~\"factorio_fluid_production_input|factorio_fluid_production_output\"},force)"
    }
   },
   {
    "name": "Fluid",
    "label": "Fluid",
    "query": {
     "query": "label_values({__name__=~\"factorio_fluid_production_input|factorio_fluid_production_output\"},name)"
    }
   },
   {
    "name": "helper_top_production",
    "label": "helper_top_production",
    "query": {
     "query": "query_result(topk(6,rate(factorio_fluid_production_output{force=~\"${Force}\",name=~\"${Fluid}\"}[$__range]) * ${TimeScale}))"
    }
   },
   {
    "name": "helper_top_consumption",
    "label": "helper_top_consumption",
    "query": {
     "query": "query_result(topk(6,rate(factorio_fluid_production_input{force=~\"${Force}\",name=~\"${Fluid}\"}[$__range]) * ${TimeScale}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Production",
   "type": "timeseries",
   "description": "Fluid production",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(factorio_fluid_production_output{force=~\"${Force}\",name=~\"${Fluid}\"}[$__rate_interval]) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "timeseries",
   "description": "Fluid consumtion",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(factorio_fluid_production_input{force=~\"${Force}\",name=~\"${Fluid}\"}[$__rate_interval]) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${helper_top_production}",
   "type": "stat",
   "description": "Overall produced ${helper_top_production}",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "repeat": "helper_top_production",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (increase(factorio_fluid_production_output{force=~\"${Force}\",name=\"${helper_top_production}\"}[$__range]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Production per ${TimeScale}",
   "type": "bargauge",
   "description": "Top produced fluid",
   "gridPos": { "h": 12, "w": 10, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,rate(factorio_fluid_production_output{force=~\"${Force}\",name=~\"${Fluid}\"}[$__range]) * ${TimeScale})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${helper_top_consumption}",
   "type": "stat",
   "description": "Overall consumed ${helper_top_consumption}",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 11 },
   "repeat": "helper_top_consumption",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (increase(factorio_fluid_production_input{force=~\"${Force}\",name=\"${helper_top_consumption}\"}[$__range]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Consumption per ${TimeScale}",
   "type": "bargauge",
   "description": "Top consumed fluid",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,rate(factorio_fluid_production_input{force=~\"${Force}\",name=~\"${Fluid}\"}[$__range]) * ${TimeScale})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}