{
 "title": "1.4 - Default: Buildings",
 "tags": [
  "factorio",
  "default"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "TimeScale",
    "label": "TimeScale",
    "query": "Second : 1, Minute : 60, Hour : 3600"
   },
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values({__name__=~\"factorio_entity_build_count_input|factorio_entity_build_count_output\"},force)"
    }
   },
   {
    "name": "Building",
    "label": "Building",
    "query": {
     "query": "label_values({__name__=~\"factorio_entity_build_count_input|factorio_entity_build_count_output\"},name)"
    }
   },
   {
    "name": "helper_top_building",
    "label": "helper_top_building",
    "query": {
     "query": "query_result(topk(6,rate(factorio_entity_build_count_input{force=~\"${Force}\", name=~\"${Building}\"}[$__range]) * ${TimeScale}))"
    }
   },
   {
    "name": "helper_top_deconstructed",
    "label": "helper_top_deconstructed",
    "query": {
     "query": "query_result(topk(6,rate(factorio_entity_build_count_output{force=~\"${Force}\", name=~\"${Building}\"}[$__range]) * ${TimeScale}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Build",
   "type": "timeseries",
   "description": "Building build",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(factorio_entity_build_count_input{force=~\"${Force}\",name=~\"${Building}\"}[$__rate_interval]) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Deconstructed",
   "type": "timeseries",
   "description": "Building deconstructed",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(factorio_entity_build_count_output{force=~\"${Force}\",name=~\"${Building}\"}[$__rate_interval]) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${helper_top_building}",
   "type": "stat",
   "description": "Overall build ${helper_top_building}",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "repeat": "helper_top_building",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (increase(factorio_entity_build_count_input{force=~\"${Force}\",name=~\"${helper_top_building}\"}[$__range]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Build  per ${TimeScale}",
   "type": "bargauge",
   "description": "Top build building",
   "gridPos": { "h": 12, "w": 10, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,rate(factorio_entity_build_count_input{force=~\"${Force}\",name=~\"${Building}\"}[$__range]) * ${TimeScale})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${helper_top_deconstructed}",
   "type": "stat",
   "description": "Overall deconstructed ${helper_top_deconstructed}",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 11 },
   "repeat": "helper_top_deconstructed",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (increase(factorio_entity_build_count_output{force=~\"${Force}\",name=~\"${helper_top_deconstructed}\"}[$__range]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Deconstructed per ${TimeScale}",
   "type": "bargauge",
   "description": "Top deconstructed building",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,rate(factorio_entity_build_count_output{name=~\"${Building}\"}[$__range]) * ${TimeScale})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}