{
 "title": "1.5 - Default: Pollution",
 "tags": [
  "factorio",
  "default"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "TimeScale",
    "label": "TimeScale",
    "query": "Second : 1, Minute : 60, Hour : 3600"
   },
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values({__name__=~\"factorio_pollution_production_input|factorio_pollution_production_output\"},force)"
    }
   },
   {
    "name": "Producer",
    "label": "Producer",
    "query": {
     "query": "label_values(factorio_pollution_production_input{force=~\"${Force}\"},name)"
    }
   },
   {
    "name": "Consumer",
    "label": "Consumer",
    "query": {
     "query": "label_values(factorio_pollution_production_output{force=~\"${Force}\"},name)"
    }
   },
   {
    "name": "helper_top_producer",
    "label": "helper_top_producer",
    "query": {
     "query": "query_result(topk(6,sum by (name) (rate(factorio_pollution_production_input{force=~\"${Force}\", name=~\"^${Producer}\"}[$__range]))))"
    }
   },
   {
    "name": "helper_top_consumer",
    "label": "helper_top_consumer",
    "query": {
     "query": "query_result(topk(6,sum by (name) (rate(factorio_pollution_production_output{force=~\"${Force}\", name=~\"^${Consumer}\"}[$__range]))))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Production",
   "type": "timeseries",
   "description": "Pollution production",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(factorio_pollution_production_input{force=~\"${Force}\",name=~\"${Producer}\"}[$__rate_interval]) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "timeseries",
   "description": "Production consumption",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(factorio_pollution_production_output{force=~\"${Force}\",name=~\"${Consumer}\"}[$__rate_interval]) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${helper_top_producer}",
   "type": "stat",
   "description": "Overall produced pollution from ${helper_top_producer}",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "repeat": "helper_top_producer",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (increase(factorio_pollution_production_input{force=~\"${Force}\",name=\"${helper_top_producer}\"}[$__range])) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": " Production per ${TimeScale}",
   "type": "bargauge",
   "description": "Top pollution producer",
   "gridPos": { "h": 12, "w": 10, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,rate(factorio_pollution_production_input{force=~\"${Force}\",name=~\"${Producer}\"}[$__range])*${TimeScale})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${helper_top_consumer}",
   "type": "stat",
   "description": "Overall consumed pollution from ${helper_top_consumer}",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 11 },
   "repeat": "helper_top_consumer",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (increase(factorio_pollution_production_output{force=~\"${Force}\",name=\"${helper_top_consumer}\"}[$__range])) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": " Consumption per ${TimeScale}",
   "type": "bargauge",
   "description": "Top pollution consumer",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,rate(factorio_pollution_production_output{force=~\"${Force}\",name=~\"${Consumer}\"}[$__range]) * ${TimeScale})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}