{
 "title": "1.6 - Default: Kills",
 "tags": [
  "factorio",
  "default"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "TimeScale",
    "label": "TimeScale",
    "query": "Second : 1, Minute : 60, Hour : 3600"
   },
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values({__name__=~ \"factorio_kill_count_input|factorio_kill_count_output\"},force)"
    }
   },
   {
    "name": "Kill",
    "label": "Kill",
    "query": {
     "query": "label_values(factorio_kill_count_input{force=~\"${Force}\"},name)"
    }
   },
   {
    "name": "Loss",
    "label": "Loss",
    "query": {
     "query": "label_values(factorio_kill_count_output{force=~\"${Force}\"},name)"
    }
   },
   {
    "name": "helper_top_kills",
    "label": "helper_top_kills",
    "query": {
     "query": "query_result(topk(6,rate(factorio_kill_count_input{force=~\"${Force}\", name=~\"${Kill}\"}[$__range]) * ${TimeScale}))"
    }
   },
   {
    "name": "helper_top_losses",
    "label": "helper_top_losses",
    "query": {
     "query": "query_result(topk(6,rate(factorio_kill_count_output{force=~\"${Force}\", name=~\"${Loss}\"}[$__range]) * ${TimeScale}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kills",
   "type": "timeseries",
   "description": "Entity killed",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(factorio_kill_count_input{force=~\"${Force}\",name=~\"${Kill}\"}[$__rate_interval]) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Losses",
   "type": "timeseries",
   "description": "Entity losses",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(factorio_kill_count_output{force=~\"${Force}\",name=~\"${Loss}\"}[$__rate_interval]) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${helper_top_kills}",
   "type": "stat",
   "description": "Overall kills ${helper_top_kills}",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 11 },
   "repeat": "helper_top_kills",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (increase(factorio_kill_count_input{force=~\"${Force}\",name=\"${helper_top_kills}\"}[$__range]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Kills per ${TimeScale}",
   "type": "bargauge",
   "description": "Top killed entities",
   "gridPos": { "h": 12, "w": 10, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,rate(factorio_kill_count_input{force=~\"${Force}\",name=~\"${Kill}\"}[$__range]) * ${TimeScale})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "${helper_top_losses}",
   "type": "stat",
   "description": "Overall losses ${helper_top_losses}",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 11 },
   "repeat": "helper_top_losses",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (increase(factorio_kill_count_output{force=~\"${Force}\",name=\"${helper_top_losses}\"}[$__range]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Losses per ${TimeScale}",
   "type": "bargauge",
   "description": "Top lost entities",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,rate(factorio_kill_count_output{force=~\"${Force}\",name=~\"${Loss}\"}[$__range]) * ${TimeScale})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}