{
 "title": "2.0.5 - Rate: Pollution",
 "tags": [
  "factorio",
  "rate"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "TimeScale",
    "label": "TimeScale",
    "query": "Second : 1, Minute : 60, Hour : 3600"
   },
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values({__name__=~\"factorio_pollution_production_input|factorio_pollution_production_output\"},force)"
    }
   },
   {
    "name": "Producer",
    "label": "Producer",
    "query": {
     "query": "label_values(factorio_pollution_production_input{force=~\"${Force}\"},name)"
    }
   },
   {
    "name": "Consumer",
    "label": "Consumer",
    "query": {
     "query": "label_values(factorio_pollution_production_output{force=~\"${Force}\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pollution Rate",
   "type": "timeseries",
   "description": "Pollution production - consumption delta",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(factorio_pollution_production_input{force=~\"${Force}\",name=~\"${Producer}\"}[$__rate_interval]) * ${TimeScale})",
     "legendFormat": "Production"
    },
    {
     "expr": "sum(rate(factorio_pollution_production_output{force=~\"${Force}\",name=~\"${Consumer}\"}[$__rate_interval]) * ${TimeScale})",
     "legendFormat": "Consumption"
    }
   ]
  },
  {
   "title": "Pollution Production",
   "type": "piechart",
   "description": "Pollution production composition",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_pollution_production_input{force=~\"${Force}\",name=~\"${Producer}\"}[$__rate_interval]) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pollution Consumption",
   "type": "piechart",
   "description": "Pollution consumption composition",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_pollution_production_output{force=~\"${Force}\",name=~\"${Consumer}\"}[$__rate_interval]) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "differentiated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pollution Production",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "rate(factorio_pollution_production_input{force=~\"${Force}\",name=~\"${Producer}\"}[$__rate_interval]) * ${TimeScale}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pollution Consumption",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(factorio_pollution_production_output{force=~\"${Force}\",name=~\"${Consumer}\"}[$__rate_interval]) * ${TimeScale}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}