{
 "title": "2.0.1 - Rate: Electricity",
 "tags": [
  "factorio",
  "rate"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values({__name__=~\"factorio_power_production_input|factorio_power_production_output\"},force)"
    }
   },
   {
    "name": "Network",
    "label": "Network",
    "query": {
     "query": "label_values({__name__=~\"factorio_power_production_input|factorio_power_production_output\"},network)"
    }
   },
   {
    "name": "Consumer",
    "label": "Consumer",
    "query": {
     "query": "label_values(factorio_power_production_input{force=~\"$Force\",network=~\"^$Network\"}, name)"
    }
   },
   {
    "name": "Producer",
    "label": "Producer",
    "query": {
     "query": "label_values(factorio_power_production_output{force=~\"${Force}\",network=~\"^${Network}\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Electricity Rate",
   "type": "timeseries",
   "description": "Electricity production - consumption delta",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(rate(factorio_power_production_output{force=~\"${Force}\",network=~\"${Network}\",name=~\"${Consumer}|${Producer}\"}[$__rate_interval]))",
     "legendFormat": "Production"
    },
    {
     "expr": "sum(rate(factorio_power_production_input{force=~\"${Force}\",network=~\"${Network}\",name=~\"${Consumer}|${Producer}\"}[$__rate_interval]))",
     "legendFormat": "Consumption"
    }
   ]
  },
  {
   "title": "Electricity Production",
   "type": "piechart",
   "description": "Electricity production composition",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (rate(factorio_power_production_output{force=~\"${Force}\",network=~\"${Network}\",name=~\"${Consumer}|${Producer}\"}[$__range]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Electricity Consumption",
   "type": "piechart",
   "description": "Electricity consumption composition",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (rate(factorio_power_production_input{force=~\"${Force}\",network=~\"${Network}\",name=~\"${Consumer}|${Producer}\"}[$__range]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "differentiated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Electricity Production",
     "type": "timeseries",
     "description": "Electricity production",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum by (name) (rate(factorio_power_production_output{force=~\"${Force}\",network=~\"${Network}\",name=~\"${Producer}\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Electricity Consumption",
     "type": "timeseries",
     "description": "Electricity consumption",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum by (name) (rate(factorio_power_production_input{force=~\"${Force}\",network=~\"${Network}\",name=~\"${Consumer}\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}