{
 "title": "2.0.2.2 - Rate: Science Packs",
 "tags": [
  "factorio",
  "rate"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "TimeScale",
    "label": "TimeScale",
    "query": "Second : 1, Minute : 60, Hour : 3600"
   },
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values(factorio_logistic_network_items,force)"
    }
   },
   {
    "name": "Surface",
    "label": "Surface",
    "query": {
     "query": "label_values(factorio_logistic_network_items{force=~\"${Force}\"},location)"
    }
   },
   {
    "name": "Network",
    "label": "Network",
    "query": {
     "query": "label_values(factorio_logistic_network_items{force=~\"${Force}\",location=~\"${Surface}\"},network)"
    }
   },
   {
    "name": "Science",
    "label": "Science",
    "query": {
     "query": "label_values(factorio_logistic_network_items{force=~\"${Force}\",location=~\"${Surface}\",network=~\"${Network}\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Science Pack Rate",
   "type": "timeseries",
   "description": "Science pack production - consumption delta",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "  rate(factorio_item_production_input{force=~\"${Force}\",name=~\"${Science}\"}[$__rate_interval]) * ${TimeScale}\r\n-\r\n  rate(factorio_item_production_output{force=~\"${Force}\",name=~\"${Science}\"}[$__rate_interval]) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Science Pack Storage",
   "type": "timeseries",
   "description": "Stored science packs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (factorio_logistic_network_items{force=~\"${Force}\", location=~\"${Surface}\", network=~\"${Network}\", name=~\"${Science}\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "differentiated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Science Pack Production",
     "type": "timeseries",
     "description": "Science pack production",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(factorio_item_production_input{force=~\"${Force}\",name=~\"${Science}\"}[$__rate_interval]) * ${TimeScale}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Science Packs Consumption",
     "type": "timeseries",
     "description": "Science packs consumption",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(factorio_item_production_output{force=~\"${Force}\",name=~\"${Science}\"}[$__rate_interval]) * ${TimeScale}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}