{
 "title": "2.0.4 - Rate: Buildings",
 "tags": [
  "factorio",
  "rate"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "TimeScale",
    "label": "TimeScale",
    "query": "Second : 1, Minute : 60, Hour : 3600"
   },
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values({__name__=~\"factorio_item_production_input|factorio_item_production_output\"},force)"
    }
   },
   {
    "name": "Building",
    "label": "Building",
    "query": {
     "query": "label_values({__name__=~\"factorio_entity_build_count_input|factorio_entity_build_count_output\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Building Rate",
   "type": "timeseries",
   "description": "Building build - deconstruction - destroyed delta",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "  rate(factorio_entity_build_count_input{force=~\"${Force}\",name=~\"${Building}\"}[$__rate_interval]) * ${TimeScale}\r\n-\r\n  (rate(factorio_entity_build_count_output{force=~\"${Force}\",name=~\"${Building}\"}[$__rate_interval]) * ${TimeScale} + rate(factorio_kill_count_output{force=~\"${Force}\",name=~\"${Building}\"}[$__rate_interval]) * ${TimeScale})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "differentiated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Building Destroyed",
     "type": "timeseries",
     "description": "Building destroyed",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(factorio_kill_count_output{force=~\"${Force}\", name=~\"${Building}\", name!~\".*-spawner|.*-worm-.*|.*-biter.*|.*-spitter.*|tree-.*|.*rock-.*|.*-robot\"}[$__rate_interval]) * ${TimeScale}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Building Construction",
     "type": "timeseries",
     "description": "Building build",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(factorio_entity_build_count_input{force=~\"${Force}\", name=~\"${Building}\"}[$__rate_interval]) * ${TimeScale}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Building Deconstruction",
     "type": "timeseries",
     "description": "Building deconstruction",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(factorio_entity_build_count_output{force=~\"${Force}\", name=~\"${Building}\"}[$__rate_interval]) * ${TimeScale}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}