{
 "title": "2.0.2 - Rate: Items",
 "tags": [
  "factorio",
  "rate"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "TimeScale",
    "label": "TimeScale",
    "query": "Second : 1, Minute : 60, Hour : 3600"
   },
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values({__name__=~\"factorio_item_production_input|factorio_item_production_output\"},force)"
    }
   },
   {
    "name": "Item",
    "label": "Item",
    "query": {
     "query": "label_values({__name__=~\"factorio_item_production_input|factorio_item_production_output\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Item Rate",
   "type": "timeseries",
   "description": "Item production - consumption delta",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "  rate(factorio_item_production_input{force=~\"${Force}\",name=~\"${Item}\"}[$__rate_interval]) * ${TimeScale}\r\n-\r\n  rate(factorio_item_production_output{force=~\"${Force}\",name=~\"${Item}\"}[$__rate_interval]) * ${TimeScale}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "differentiated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Item Production",
     "type": "timeseries",
     "description": "Item production",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(factorio_item_production_input{force=~\"${Force}\",name=~\"${Item}\"}[$__rate_interval]) * ${TimeScale}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Item Consumption",
     "type": "timeseries",
     "description": "Item consumption",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(factorio_item_production_output{force=~\"${Force}\",name=~\"${Item}\"}[$__rate_interval]) * ${TimeScale}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}