{
 "title": "3.0.4.2 - Misc: Robots",
 "tags": [
  "factorio",
  "misc"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values(factorio_logistic_network_robot_limit,force)"
    }
   },
   {
    "name": "Surface",
    "label": "Surface",
    "query": {
     "query": "label_values(factorio_logistic_network_robot_limit{force=~\"${Force}\"},location)"
    }
   },
   {
    "name": "Network",
    "label": "Network",
    "query": {
     "query": "label_values(factorio_logistic_network_robot_limit{force=~\"${Force}\",location=~\"${Surface}\"},network)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network Construction Robots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network ${Network}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "repeat": "Network",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(\r\n    factorio_logistic_network_all_construction_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\r\n  )\r\nor on ()\r\n  vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network Logistic Robots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Network ${Network}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "repeat": "Network",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(\r\n    factorio_logistic_network_all_logistic_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\r\n  )\r\nor on ()\r\n  vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network ${Network} Construction Robots:",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "Network",
   "collapsed": true,
   "panels": [
    {
     "title": "Total Construction Robots",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "  sum(\n    factorio_logistic_network_all_construction_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\n  )\nor on ()\n  vector(0)",
       "legendFormat": "Overall"
      }
     ]
    },
    {
     "title": "Available Construction Robots",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n    factorio_logistic_network_available_construction_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\n  /\n    factorio_logistic_network_all_construction_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Working Construction Robots",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "  sum(\r\n      factorio_logistic_network_all_construction_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\r\n    -\r\n      factorio_logistic_network_available_construction_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\r\n  )\r\nor on ()\r\n  vector(0)",
       "legendFormat": "Working"
      }
     ]
    },
    {
     "title": "Available Construction Robots",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "  sum(\n    factorio_logistic_network_available_construction_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\n  )\nor on ()\n  vector(0)",
       "legendFormat": "Available"
      }
     ]
    }
   ]
  },
  {
   "title": "Network ${Network} Logistic Robots:",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "repeat": "Network",
   "collapsed": true,
   "panels": [
    {
     "title": "Total Logistic Robots",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "  sum(\n    factorio_logistic_network_all_logistic_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\n  )\nor on ()\n  vector(0)",
       "legendFormat": "Overall"
      }
     ]
    },
    {
     "title": "Available Logistic Robots",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\r\n    factorio_logistic_network_available_logistic_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\r\n  /\r\n    factorio_logistic_network_all_logistic_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Working Logistic Robots",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "  sum(\r\n      factorio_logistic_network_all_logistic_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\r\n    -\r\n      factorio_logistic_network_available_logistic_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\r\n  )\r\nor on ()\r\n  vector(0)",
       "legendFormat": "Working"
      }
     ]
    },
    {
     "title": "Available Logistic Robots",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "  sum(\n    factorio_logistic_network_available_logistic_robots{force=~\"${Force}\",location=~\"${Surface}\",network=\"${Network}\"}\n  )\nor on ()\n  vector(0)",
       "legendFormat": "Available"
      }
     ]
    }
   ]
  }
 ]
}