{
 "title": "3.0.5 - Misc: Trains",
 "tags": [
  "factorio",
  "misc"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "TrainID",
    "label": "TrainID",
    "query": {
     "query": "label_values(factorio_train_trip_time,train_id)"
    }
   },
   {
    "name": "Station",
    "label": "Station",
    "query": {
     "query": "label_values(factorio_train_arrival_time,station)"
    }
   },
   {
    "name": "From",
    "label": "From",
    "query": {
     "query": "label_values(factorio_train_trip_time{train_id=~\"^${TrainID}\"},from)"
    }
   },
   {
    "name": "To",
    "label": "To",
    "query": {
     "query": "label_values(factorio_train_trip_time{from=~\"^${From}\"},to)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Station Arrival TIme",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "factorio_train_arrival_time{station=~\"${Station}\"}",
     "legendFormat": "{{station}}"
    }
   ]
  },
  {
   "title": "Train Loop TIme",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "factorio_train_direct_loop_time{a=~\"${From}\",b=~\"${To}\"}",
     "legendFormat": "{{a}} -> {{b}}"
    }
   ]
  },
  {
   "title": "Train Trip Time",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "factorio_train_trip_time{from=~\"${From}\",to=~\"${To}\",train_id=~\"${TrainID}\"}",
     "legendFormat": "{{train_id}}: {{from}} -> {{to}}"
    }
   ]
  },
  {
   "title": "Train Wait Time",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "factorio_train_wait_time{from=~\"${From}\",to=~\"${To}\",train_id=~\"${TrainID}\"}",
     "legendFormat": "{{train_id}}: {{from}} -> {{to}}"
    }
   ]
  }
 ]
}